name:                hMAC
version:             0.1.0.0
github:              "xTeKc/hMAC"
license:             Apache-2.0
author:              "xTeKc"
maintainer:          ""
copyright:           "2021 xTeKc"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/hMAC#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- scotty
- clash-prelude

library:
  source-dirs: src

executables:
  hMAC-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hMAC
    - aeson
    - scotty
    - clash-prelude

tests:
  hMAC-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hMAC
    - aeson
    - scotty
    - clash-prelude
